"""create trade table

Revision ID: 9eefa8355aed
Revises: 
Create Date: 2026-05-29 18:51:38.483636

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9eefa8355aed'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quote_quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_buyer_maker', sa.Boolean(), nullable=False),
    sa.Column('is_best_match', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id')
    )
    op.create_index('ix_trades_symbol', 'trades', ['symbol'], unique=False)
    op.create_index('ix_trades_symbol_time', 'trades', ['symbol', 'time'], unique=False)
    op.create_index('ix_trades_time', 'trades', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_time', table_name='trades')
    op.drop_index('ix_trades_symbol_time', table_name='trades')
    op.drop_index('ix_trades_symbol', table_name='trades')
    op.drop_table('trades')
    # ### end Alembic commands ###
